// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package decoder

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __native_entry__() uintptr

var (
    _subr__do_skip = __native_entry__() + 13
)

var (
    _ = _subr__do_skip
)
