// Copyright 2022 ByteDance Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/cloudwego/thriftgo/generator/backend"
	"github.com/cloudwego/thriftgo/generator/golang"
	"github.com/cloudwego/thriftgo/parser"
	"github.com/cloudwego/thriftgo/plugin"
)

type generator struct {
	req      *plugin.Request
	warnings []string
	utils    *golang.CodeUtils
}

func newGenerator(req *plugin.Request) *generator {
	g := &generator{req: req}
	cu := golang.NewCodeUtils(backend.LogFunc{
		Warn: g.warn,
		Info: func(v ...interface{}) {
			// do nothing
		},
		MultiWarn: func(warns []string) {
			g.warnings = append(g.warnings, warns...)
		},
	})
	cu.HandleOptions(req.GeneratorParameters)
	g.utils = cu
	return g
}

func (g *generator) generate() (generated []*plugin.Generated, err error) {
	trees := make(map[string]*parser.Thrift)
	var addThrift func(ast *parser.Thrift)
	addThrift = func(ast *parser.Thrift) {
		if _, ok := trees[ast.Filename]; ok {
			return
		}
		trees[ast.Filename] = ast
		for _, inc := range ast.Includes {
			addThrift(inc.Reference)
		}
	}
	addThrift(g.req.AST)
	for _, tree := range trees {
		gens, err := g.genOneFile(tree)
		if err != nil {
			return nil, err
		}
		generated = append(generated, gens...)
	}
	return generated, nil
}

func (g *generator) renderTestFile(scope *golang.Scope, tree *parser.Thrift) (*plugin.Generated, error) {
	structCounter := make(map[string]int)
	gen := NewGenerated()
	path := filepath.Join(g.req.OutputPath, g.utils.GetFilePath(tree))
	path = strings.TrimSuffix(path, ".go") + "_test.go"

	gen.P(`// Code generated by thrift-gen-ftb. DO NOT EDIT.`)
	gen.P("package ", g.utils.GetPackageName(tree))
	gen.P(`import (
	"bytes"
	"reflect"
	"testing"
	"strings"

	"github.com/cloudwego/frugal"
	diff "github.com/r3labs/diff/v3"
	gofakeit "github.com/simon0-o/gofakeit/v6"
	"github.com/stretchr/testify/assert"
)

var (
	_ = bytes.Equal
	_ = testing.T{}
	_ = strings.HasPrefix
	_ = reflect.DeepEqual
	_ = gofakeit.Struct
	_ = frugal.EncodeObject
	_ = assert.Equal
	_ = diff.Diff
)`)

	for _, st := range scope.StructLikes() {
		name := fmt.Sprintf("Test%s%d", st.GoName(), structCounter[st.GoName().String()])
		structCounter[st.GoName().String()]++
		gen.P("func ", name, "(t *testing.T) {")
		gen.P("s := &", st.GoName(), "{}")
		gen.P(`gofakeit.Struct(s)
length := s.BLength()
want := make([]byte, length)
got := make([]byte, frugal.EncodedSize(s))
s.FastWriteNocopy(want, nil)
_, err := frugal.EncodeObject(got, nil, s)
if err != nil {
	t.Error(err)
}`)
		gen.P("wantS := New", st.GoName(), "()")
		gen.P("gotS := New", st.GoName(), "()")
		gen.P(`_, fastErr := wantS.FastRead(want)
_, err = frugal.DecodeObject(got, gotS)
if err == nil {
	if !reflect.DeepEqual(wantS, gotS) {
		dlog, _ := diff.Diff(wantS, gotS)
		assert.True(t, len(dlog) == 0)
	}
} else if fastErr == nil {
	t.Error(err)
}`)
		gen.P("}")
	}

	return &plugin.Generated{
		Content: gen.Out(),
		Name:    &path,
	}, nil
}

func (g *generator) renderStructTags(scope *golang.Scope, tree *parser.Thrift) ([]*plugin.Generated, error) {
	var ret []*plugin.Generated
	path := filepath.Join(g.req.OutputPath, g.utils.GetFilePath(tree))

	for _, st := range scope.StructLikes() {
		insertPointPrefix := st.Category + "." + st.Name
		for fn, fi := range st.Fields() {
			insertPoint := insertPointPrefix + "." + fi.Name + ".tag"
			var tag string
			// compose tag
			var hasStructMapKey bool
			var checkMapKey func(typ *parser.Type)
			checkMapKey = func(typ *parser.Type) {
				if fi.Type.Category == parser.Category_Map {
					if fi.Type.KeyType.Category == parser.Category_Struct {
						hasStructMapKey = true
						return
					}
				}
				if typ.KeyType != nil && typ.KeyType.Category.IsContainerType() {
					checkMapKey(typ.KeyType)
				}
				if typ.ValueType != nil && typ.ValueType.Category.IsContainerType() {
					checkMapKey(typ.ValueType)
				}
			}
			checkMapKey(fi.Type)
			selfReference := st.Name == fi.Type.Name
			unionSkip := st.Category == "union" && fn != 0
			if hasStructMapKey || selfReference || unionSkip {
				tag = " fake:\"skip\""
			}
			if fi.Type.Category.IsContainerType() {
				tag += " fakesize:\"2\""
			}
			if tag != "" {
				ret = append(ret, &plugin.Generated{
					Content:        tag,
					Name:           &path,
					InsertionPoint: &insertPoint,
				})
			}
		}
	}

	return ret, nil
}

func (g *generator) genOneFile(tree *parser.Thrift) ([]*plugin.Generated, error) {
	var generated []*plugin.Generated
	scope, err := golang.BuildScope(g.utils, tree)
	if err != nil {
		return nil, err
	}
	g.utils.SetRootScope(scope)
	testFile, err := g.renderTestFile(scope, tree)
	if err != nil {
		return nil, err
	}
	generated = append(generated, testFile)
	tags, err := g.renderStructTags(scope, tree)
	if err != nil {
		return nil, err
	}
	generated = append(generated, tags...)
	return generated, nil
}

func (g *generator) warn(v ...interface{}) {
	g.warnings = append(g.warnings, fmt.Sprintln(v...))
}

func (g *generator) warnf(format string, v ...interface{}) {
	g.warnings = append(g.warnings, fmt.Sprintf(format, v...))
}

type generated struct {
	buf bytes.Buffer
}

func NewGenerated() *generated {
	return &generated{}
}

func (g *generated) P(v ...interface{}) {
	for _, x := range v {
		fmt.Fprint(&g.buf, x)
	}
	fmt.Fprintln(&g.buf)
}

func (g *generated) Out() string {
	return g.buf.String()
}
