// Code generated by gen_map_fast_compact.go. DO NOT EDIT.

package reflect

import (
	"math"
	"unsafe"
)

func appendBoolCompact(b []byte, v bool) ([]byte, error) {
	if v {
		return append(b, byte(ctBOOL_TRUE)), nil
	}
	return append(b, byte(ctBOOL_FALSE)), nil
}

func init() {
	registerMapAppendFuncCompact(tBOOL, tBOOL, appendMapCompact_BOOL_BOOL)
	registerMapAppendFuncCompact(tBOOL, tI08, appendMapCompact_BOOL_I08)
	registerMapAppendFuncCompact(tBOOL, tI16, appendMapCompact_BOOL_I16)
	registerMapAppendFuncCompact(tBOOL, tI32, appendMapCompact_BOOL_I32)
	registerMapAppendFuncCompact(tBOOL, tI64, appendMapCompact_BOOL_I64)
	registerMapAppendFuncCompact(tBOOL, tDOUBLE, appendMapCompact_BOOL_DOUBLE)
	registerMapAppendFuncCompact(tBOOL, tENUM, appendMapCompact_BOOL_ENUM)
	registerMapAppendFuncCompact(tBOOL, tSTRING, appendMapCompact_BOOL_STRING)
	registerMapAppendFuncCompact(tBOOL, tSTRUCT, appendMapCompact_BOOL_STRUCT)
	registerMapAppendFuncCompact(tBOOL, tMAP, appendMapCompact_BOOL_MAP)
	registerMapAppendFuncCompact(tBOOL, tSET, appendMapCompact_BOOL_SET)
	registerMapAppendFuncCompact(tBOOL, tLIST, appendMapCompact_BOOL_LIST)
	registerMapAppendFuncCompact(tI08, tBOOL, appendMapCompact_I08_BOOL)
	registerMapAppendFuncCompact(tI08, tI08, appendMapCompact_I08_I08)
	registerMapAppendFuncCompact(tI08, tI16, appendMapCompact_I08_I16)
	registerMapAppendFuncCompact(tI08, tI32, appendMapCompact_I08_I32)
	registerMapAppendFuncCompact(tI08, tI64, appendMapCompact_I08_I64)
	registerMapAppendFuncCompact(tI08, tDOUBLE, appendMapCompact_I08_DOUBLE)
	registerMapAppendFuncCompact(tI08, tENUM, appendMapCompact_I08_ENUM)
	registerMapAppendFuncCompact(tI08, tSTRING, appendMapCompact_I08_STRING)
	registerMapAppendFuncCompact(tI08, tSTRUCT, appendMapCompact_I08_STRUCT)
	registerMapAppendFuncCompact(tI08, tMAP, appendMapCompact_I08_MAP)
	registerMapAppendFuncCompact(tI08, tSET, appendMapCompact_I08_SET)
	registerMapAppendFuncCompact(tI08, tLIST, appendMapCompact_I08_LIST)
	registerMapAppendFuncCompact(tI16, tBOOL, appendMapCompact_I16_BOOL)
	registerMapAppendFuncCompact(tI16, tI08, appendMapCompact_I16_I08)
	registerMapAppendFuncCompact(tI16, tI16, appendMapCompact_I16_I16)
	registerMapAppendFuncCompact(tI16, tI32, appendMapCompact_I16_I32)
	registerMapAppendFuncCompact(tI16, tI64, appendMapCompact_I16_I64)
	registerMapAppendFuncCompact(tI16, tDOUBLE, appendMapCompact_I16_DOUBLE)
	registerMapAppendFuncCompact(tI16, tENUM, appendMapCompact_I16_ENUM)
	registerMapAppendFuncCompact(tI16, tSTRING, appendMapCompact_I16_STRING)
	registerMapAppendFuncCompact(tI16, tSTRUCT, appendMapCompact_I16_STRUCT)
	registerMapAppendFuncCompact(tI16, tMAP, appendMapCompact_I16_MAP)
	registerMapAppendFuncCompact(tI16, tSET, appendMapCompact_I16_SET)
	registerMapAppendFuncCompact(tI16, tLIST, appendMapCompact_I16_LIST)
	registerMapAppendFuncCompact(tI32, tBOOL, appendMapCompact_I32_BOOL)
	registerMapAppendFuncCompact(tI32, tI08, appendMapCompact_I32_I08)
	registerMapAppendFuncCompact(tI32, tI16, appendMapCompact_I32_I16)
	registerMapAppendFuncCompact(tI32, tI32, appendMapCompact_I32_I32)
	registerMapAppendFuncCompact(tI32, tI64, appendMapCompact_I32_I64)
	registerMapAppendFuncCompact(tI32, tDOUBLE, appendMapCompact_I32_DOUBLE)
	registerMapAppendFuncCompact(tI32, tENUM, appendMapCompact_I32_ENUM)
	registerMapAppendFuncCompact(tI32, tSTRING, appendMapCompact_I32_STRING)
	registerMapAppendFuncCompact(tI32, tSTRUCT, appendMapCompact_I32_STRUCT)
	registerMapAppendFuncCompact(tI32, tMAP, appendMapCompact_I32_MAP)
	registerMapAppendFuncCompact(tI32, tSET, appendMapCompact_I32_SET)
	registerMapAppendFuncCompact(tI32, tLIST, appendMapCompact_I32_LIST)
	registerMapAppendFuncCompact(tI64, tBOOL, appendMapCompact_I64_BOOL)
	registerMapAppendFuncCompact(tI64, tI08, appendMapCompact_I64_I08)
	registerMapAppendFuncCompact(tI64, tI16, appendMapCompact_I64_I16)
	registerMapAppendFuncCompact(tI64, tI32, appendMapCompact_I64_I32)
	registerMapAppendFuncCompact(tI64, tI64, appendMapCompact_I64_I64)
	registerMapAppendFuncCompact(tI64, tDOUBLE, appendMapCompact_I64_DOUBLE)
	registerMapAppendFuncCompact(tI64, tENUM, appendMapCompact_I64_ENUM)
	registerMapAppendFuncCompact(tI64, tSTRING, appendMapCompact_I64_STRING)
	registerMapAppendFuncCompact(tI64, tSTRUCT, appendMapCompact_I64_STRUCT)
	registerMapAppendFuncCompact(tI64, tMAP, appendMapCompact_I64_MAP)
	registerMapAppendFuncCompact(tI64, tSET, appendMapCompact_I64_SET)
	registerMapAppendFuncCompact(tI64, tLIST, appendMapCompact_I64_LIST)
	registerMapAppendFuncCompact(tDOUBLE, tBOOL, appendMapCompact_DOUBLE_BOOL)
	registerMapAppendFuncCompact(tDOUBLE, tI08, appendMapCompact_DOUBLE_I08)
	registerMapAppendFuncCompact(tDOUBLE, tI16, appendMapCompact_DOUBLE_I16)
	registerMapAppendFuncCompact(tDOUBLE, tI32, appendMapCompact_DOUBLE_I32)
	registerMapAppendFuncCompact(tDOUBLE, tI64, appendMapCompact_DOUBLE_I64)
	registerMapAppendFuncCompact(tDOUBLE, tDOUBLE, appendMapCompact_DOUBLE_DOUBLE)
	registerMapAppendFuncCompact(tDOUBLE, tENUM, appendMapCompact_DOUBLE_ENUM)
	registerMapAppendFuncCompact(tDOUBLE, tSTRING, appendMapCompact_DOUBLE_STRING)
	registerMapAppendFuncCompact(tDOUBLE, tSTRUCT, appendMapCompact_DOUBLE_STRUCT)
	registerMapAppendFuncCompact(tDOUBLE, tMAP, appendMapCompact_DOUBLE_MAP)
	registerMapAppendFuncCompact(tDOUBLE, tSET, appendMapCompact_DOUBLE_SET)
	registerMapAppendFuncCompact(tDOUBLE, tLIST, appendMapCompact_DOUBLE_LIST)
	registerMapAppendFuncCompact(tENUM, tBOOL, appendMapCompact_ENUM_BOOL)
	registerMapAppendFuncCompact(tENUM, tI08, appendMapCompact_ENUM_I08)
	registerMapAppendFuncCompact(tENUM, tI16, appendMapCompact_ENUM_I16)
	registerMapAppendFuncCompact(tENUM, tI32, appendMapCompact_ENUM_I32)
	registerMapAppendFuncCompact(tENUM, tI64, appendMapCompact_ENUM_I64)
	registerMapAppendFuncCompact(tENUM, tDOUBLE, appendMapCompact_ENUM_DOUBLE)
	registerMapAppendFuncCompact(tENUM, tENUM, appendMapCompact_ENUM_ENUM)
	registerMapAppendFuncCompact(tENUM, tSTRING, appendMapCompact_ENUM_STRING)
	registerMapAppendFuncCompact(tENUM, tSTRUCT, appendMapCompact_ENUM_STRUCT)
	registerMapAppendFuncCompact(tENUM, tMAP, appendMapCompact_ENUM_MAP)
	registerMapAppendFuncCompact(tENUM, tSET, appendMapCompact_ENUM_SET)
	registerMapAppendFuncCompact(tENUM, tLIST, appendMapCompact_ENUM_LIST)
	registerMapAppendFuncCompact(tSTRING, tBOOL, appendMapCompact_STRING_BOOL)
	registerMapAppendFuncCompact(tSTRING, tI08, appendMapCompact_STRING_I08)
	registerMapAppendFuncCompact(tSTRING, tI16, appendMapCompact_STRING_I16)
	registerMapAppendFuncCompact(tSTRING, tI32, appendMapCompact_STRING_I32)
	registerMapAppendFuncCompact(tSTRING, tI64, appendMapCompact_STRING_I64)
	registerMapAppendFuncCompact(tSTRING, tDOUBLE, appendMapCompact_STRING_DOUBLE)
	registerMapAppendFuncCompact(tSTRING, tENUM, appendMapCompact_STRING_ENUM)
	registerMapAppendFuncCompact(tSTRING, tSTRING, appendMapCompact_STRING_STRING)
	registerMapAppendFuncCompact(tSTRING, tSTRUCT, appendMapCompact_STRING_STRUCT)
	registerMapAppendFuncCompact(tSTRING, tMAP, appendMapCompact_STRING_MAP)
	registerMapAppendFuncCompact(tSTRING, tSET, appendMapCompact_STRING_SET)
	registerMapAppendFuncCompact(tSTRING, tLIST, appendMapCompact_STRING_LIST)
	registerMapAppendFuncCompact(tSTRUCT, tBOOL, appendMapCompact_STRUCT_BOOL)
	registerMapAppendFuncCompact(tSTRUCT, tI08, appendMapCompact_STRUCT_I08)
	registerMapAppendFuncCompact(tSTRUCT, tI16, appendMapCompact_STRUCT_I16)
	registerMapAppendFuncCompact(tSTRUCT, tI32, appendMapCompact_STRUCT_I32)
	registerMapAppendFuncCompact(tSTRUCT, tI64, appendMapCompact_STRUCT_I64)
	registerMapAppendFuncCompact(tSTRUCT, tDOUBLE, appendMapCompact_STRUCT_DOUBLE)
	registerMapAppendFuncCompact(tSTRUCT, tENUM, appendMapCompact_STRUCT_ENUM)
	registerMapAppendFuncCompact(tSTRUCT, tSTRING, appendMapCompact_STRUCT_STRING)
	registerMapAppendFuncCompact(tSTRUCT, tSTRUCT, appendMapCompact_STRUCT_STRUCT)
	registerMapAppendFuncCompact(tSTRUCT, tMAP, appendMapCompact_STRUCT_MAP)
	registerMapAppendFuncCompact(tSTRUCT, tSET, appendMapCompact_STRUCT_SET)
	registerMapAppendFuncCompact(tSTRUCT, tLIST, appendMapCompact_STRUCT_LIST)
	registerMapAppendFuncCompact(tMAP, tBOOL, appendMapCompact_MAP_BOOL)
	registerMapAppendFuncCompact(tMAP, tI08, appendMapCompact_MAP_I08)
	registerMapAppendFuncCompact(tMAP, tI16, appendMapCompact_MAP_I16)
	registerMapAppendFuncCompact(tMAP, tI32, appendMapCompact_MAP_I32)
	registerMapAppendFuncCompact(tMAP, tI64, appendMapCompact_MAP_I64)
	registerMapAppendFuncCompact(tMAP, tDOUBLE, appendMapCompact_MAP_DOUBLE)
	registerMapAppendFuncCompact(tMAP, tENUM, appendMapCompact_MAP_ENUM)
	registerMapAppendFuncCompact(tMAP, tSTRING, appendMapCompact_MAP_STRING)
	registerMapAppendFuncCompact(tMAP, tSTRUCT, appendMapCompact_MAP_STRUCT)
	registerMapAppendFuncCompact(tMAP, tMAP, appendMapCompact_MAP_MAP)
	registerMapAppendFuncCompact(tMAP, tSET, appendMapCompact_MAP_SET)
	registerMapAppendFuncCompact(tMAP, tLIST, appendMapCompact_MAP_LIST)
	registerMapAppendFuncCompact(tSET, tBOOL, appendMapCompact_SET_BOOL)
	registerMapAppendFuncCompact(tSET, tI08, appendMapCompact_SET_I08)
	registerMapAppendFuncCompact(tSET, tI16, appendMapCompact_SET_I16)
	registerMapAppendFuncCompact(tSET, tI32, appendMapCompact_SET_I32)
	registerMapAppendFuncCompact(tSET, tI64, appendMapCompact_SET_I64)
	registerMapAppendFuncCompact(tSET, tDOUBLE, appendMapCompact_SET_DOUBLE)
	registerMapAppendFuncCompact(tSET, tENUM, appendMapCompact_SET_ENUM)
	registerMapAppendFuncCompact(tSET, tSTRING, appendMapCompact_SET_STRING)
	registerMapAppendFuncCompact(tSET, tSTRUCT, appendMapCompact_SET_STRUCT)
	registerMapAppendFuncCompact(tSET, tMAP, appendMapCompact_SET_MAP)
	registerMapAppendFuncCompact(tSET, tSET, appendMapCompact_SET_SET)
	registerMapAppendFuncCompact(tSET, tLIST, appendMapCompact_SET_LIST)
	registerMapAppendFuncCompact(tLIST, tBOOL, appendMapCompact_LIST_BOOL)
	registerMapAppendFuncCompact(tLIST, tI08, appendMapCompact_LIST_I08)
	registerMapAppendFuncCompact(tLIST, tI16, appendMapCompact_LIST_I16)
	registerMapAppendFuncCompact(tLIST, tI32, appendMapCompact_LIST_I32)
	registerMapAppendFuncCompact(tLIST, tI64, appendMapCompact_LIST_I64)
	registerMapAppendFuncCompact(tLIST, tDOUBLE, appendMapCompact_LIST_DOUBLE)
	registerMapAppendFuncCompact(tLIST, tENUM, appendMapCompact_LIST_ENUM)
	registerMapAppendFuncCompact(tLIST, tSTRING, appendMapCompact_LIST_STRING)
	registerMapAppendFuncCompact(tLIST, tSTRUCT, appendMapCompact_LIST_STRUCT)
	registerMapAppendFuncCompact(tLIST, tMAP, appendMapCompact_LIST_MAP)
	registerMapAppendFuncCompact(tLIST, tSET, appendMapCompact_LIST_SET)
	registerMapAppendFuncCompact(tLIST, tLIST, appendMapCompact_LIST_LIST)
}

func appendMapCompact_BOOL_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]bool)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]int8)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]int16)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]int32)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]int64)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]float64)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]int64)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[bool]string)(p) {
		n--
		b, _ = appendBoolCompact(b, k)
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, _ = appendBoolCompact(b, *(*bool)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, _ = appendBoolCompact(b, *(*bool)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, _ = appendBoolCompact(b, *(*bool)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_BOOL_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, _ = appendBoolCompact(b, *(*bool)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]bool)(p) {
		n--
		b = append(b, byte(k))
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]int8)(p) {
		n--
		b = append(b, byte(k))
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]int16)(p) {
		n--
		b = append(b, byte(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]int32)(p) {
		n--
		b = append(b, byte(k))
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]int64)(p) {
		n--
		b = append(b, byte(k))
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]float64)(p) {
		n--
		b = append(b, byte(k))
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]int64)(p) {
		n--
		b = append(b, byte(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int8]string)(p) {
		n--
		b = append(b, byte(k))
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = append(b, *(*byte)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = append(b, *(*byte)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = append(b, *(*byte)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I08_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = append(b, *(*byte)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]bool)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]int8)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]int16)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]int32)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]int64)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]float64)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]int64)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int16]string)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int16)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int16)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int16)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I16_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int16)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]bool)(p) {
		n--
		b = appendZigzag32(b, k)
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]int8)(p) {
		n--
		b = appendZigzag32(b, k)
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]int16)(p) {
		n--
		b = appendZigzag32(b, k)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]int32)(p) {
		n--
		b = appendZigzag32(b, k)
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]int64)(p) {
		n--
		b = appendZigzag32(b, k)
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]float64)(p) {
		n--
		b = appendZigzag32(b, k)
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]int64)(p) {
		n--
		b = appendZigzag32(b, k)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int32]string)(p) {
		n--
		b = appendZigzag32(b, k)
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, *(*int32)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, *(*int32)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, *(*int32)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I32_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, *(*int32)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]bool)(p) {
		n--
		b = appendZigzag64(b, k)
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int8)(p) {
		n--
		b = appendZigzag64(b, k)
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int16)(p) {
		n--
		b = appendZigzag64(b, k)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int32)(p) {
		n--
		b = appendZigzag64(b, k)
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int64)(p) {
		n--
		b = appendZigzag64(b, k)
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]float64)(p) {
		n--
		b = appendZigzag64(b, k)
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int64)(p) {
		n--
		b = appendZigzag64(b, k)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]string)(p) {
		n--
		b = appendZigzag64(b, k)
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag64(b, *(*int64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag64(b, *(*int64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag64(b, *(*int64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_I64_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag64(b, *(*int64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]bool)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]int8)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]int16)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]int32)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]int64)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]float64)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]int64)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[float64]string)(p) {
		n--
		b = appendUint64LE(b, math.Float64bits(k))
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendUint64LE(b, *(*uint64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendUint64LE(b, *(*uint64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendUint64LE(b, *(*uint64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_DOUBLE_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendUint64LE(b, *(*uint64)(kp))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]bool)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int8)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int16)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int32)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int64)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]float64)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]int64)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[int64]string)(p) {
		n--
		b = appendZigzag32(b, int32(k))
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int64)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int64)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int64)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_ENUM_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b = appendZigzag32(b, int32(*(*int64)(kp)))
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]bool)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b, _ = appendBoolCompact(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]int8)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b = append(b, byte(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]int16)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]int32)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b = appendZigzag32(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]int64)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b = appendZigzag64(b, v)
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]float64)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b = appendUint64LE(b, math.Float64bits(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]int64)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b = appendZigzag32(b, int32(v))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*map[string]string)(p) {
		n--
		b = appendVarint(b, uint64(len(k))); b = append(b, k...)
		b = appendVarint(b, uint64(len(v))); b = append(b, v...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		s := *(*string)(kp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		s := *(*string)(kp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		s := *(*string)(kp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRING_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		s := *(*string)(kp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, _ = appendBoolCompact(b, *(*bool)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = append(b, *(*byte)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int16)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, *(*int32)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag64(b, *(*int64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendUint64LE(b, *(*uint64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int64)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		s := *(*string)(vp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_STRUCT_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, _ = appendBoolCompact(b, *(*bool)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = append(b, *(*byte)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int16)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, *(*int32)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag64(b, *(*int64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendUint64LE(b, *(*uint64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int64)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		s := *(*string)(vp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_MAP_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, _ = appendBoolCompact(b, *(*bool)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = append(b, *(*byte)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int16)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, *(*int32)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag64(b, *(*int64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendUint64LE(b, *(*uint64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int64)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		s := *(*string)(vp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_SET_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_BOOL(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, _ = appendBoolCompact(b, *(*bool)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_I08(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = append(b, *(*byte)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_I16(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int16)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_I32(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, *(*int32)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_I64(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag64(b, *(*int64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_DOUBLE(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendUint64LE(b, *(*uint64)(vp))
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_ENUM(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b = appendZigzag32(b, int32(*(*int64)(vp)))
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_STRING(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		s := *(*string)(vp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_STRUCT(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_MAP(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_SET(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}

func appendMapCompact_LIST_LIST(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }
		b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }
	}
	return b, checkMapN(n)
}
