//go:build ignore

// gen_map_fast_compact.go generates Compact map fast-path functions.
// Run: go run gen_map_fast_compact.go > append_map_fast_compact.go

package main

import (
	"fmt"
	"os"
)

type typeInfo struct {
	name      string // e.g. "I32"
	goType    string // e.g. "int32"
	goMapType string // e.g. "int32" for map[int32]X
}

var scalarTypes = []typeInfo{
	{"BOOL", "bool", "bool"},
	{"I08", "int8", "int8"},
	{"I16", "int16", "int16"},
	{"I32", "int32", "int32"},
	{"I64", "int64", "int64"},
	{"DOUBLE", "float64", "float64"},
	{"ENUM", "int64", "int64"},
	{"STRING", "string", "string"},
}

var containerTypeNames = []string{"STRUCT", "MAP", "SET", "LIST"}

func compactKeyExpr(t typeInfo) string {
	switch t.name {
	case "BOOL":
		return `b, _ = appendBoolCompact(b, *(*bool)(kp))`
	case "I08":
		return `b = append(b, *(*byte)(kp))`
	case "I16":
		return `b = appendZigzag32(b, int32(*(*int16)(kp)))`
	case "I32":
		return `b = appendZigzag32(b, *(*int32)(kp))`
	case "I64":
		return `b = appendZigzag64(b, *(*int64)(kp))`
	case "DOUBLE":
		return `b = appendUint64LE(b, *(*uint64)(kp))`
	case "ENUM":
		return `b = appendZigzag32(b, int32(*(*int64)(kp)))`
	case "STRING":
		return `s := *(*string)(kp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)`
	}
	panic("unknown key type: " + t.name)
}

func compactValExpr(t typeInfo) string {
	switch t.name {
	case "BOOL":
		return `b, _ = appendBoolCompact(b, *(*bool)(vp))`
	case "I08":
		return `b = append(b, *(*byte)(vp))`
	case "I16":
		return `b = appendZigzag32(b, int32(*(*int16)(vp)))`
	case "I32":
		return `b = appendZigzag32(b, *(*int32)(vp))`
	case "I64":
		return `b = appendZigzag64(b, *(*int64)(vp))`
	case "DOUBLE":
		return `b = appendUint64LE(b, *(*uint64)(vp))`
	case "ENUM":
		return `b = appendZigzag32(b, int32(*(*int64)(vp)))`
	case "STRING":
		return `s := *(*string)(vp); b = appendVarint(b, uint64(len(s))); b = append(b, s...)`
	}
	panic("unknown val type: " + t.name)
}

func compactRangeKeyExpr(t typeInfo) string {
	switch t.name {
	case "BOOL":
		return `b, _ = appendBoolCompact(b, k)`
	case "I08":
		return `b = append(b, byte(k))`
	case "I16":
		return `b = appendZigzag32(b, int32(k))`
	case "I32":
		return `b = appendZigzag32(b, k)`
	case "I64":
		return `b = appendZigzag64(b, k)`
	case "DOUBLE":
		return `b = appendUint64LE(b, math.Float64bits(k))`
	case "ENUM":
		return `b = appendZigzag32(b, int32(k))`
	case "STRING":
		return `b = appendVarint(b, uint64(len(k))); b = append(b, k...)`
	}
	panic("unknown range key type: " + t.name)
}

func compactRangeValExpr(t typeInfo) string {
	switch t.name {
	case "BOOL":
		return `b, _ = appendBoolCompact(b, v)`
	case "I08":
		return `b = append(b, byte(v))`
	case "I16":
		return `b = appendZigzag32(b, int32(v))`
	case "I32":
		return `b = appendZigzag32(b, v)`
	case "I64":
		return `b = appendZigzag64(b, v)`
	case "DOUBLE":
		return `b = appendUint64LE(b, math.Float64bits(v))`
	case "ENUM":
		return `b = appendZigzag32(b, int32(v))`
	case "STRING":
		return `b = appendVarint(b, uint64(len(v))); b = append(b, v...)`
	}
	panic("unknown range val type: " + t.name)
}

func isScalar(name string) bool {
	for _, s := range scalarTypes {
		if s.name == name {
			return true
		}
	}
	return false
}

func main() {
	w := os.Stdout

	fmt.Fprint(w, `// Code generated by gen_map_fast_compact.go. DO NOT EDIT.

package reflect

import (
	"math"
	"unsafe"
)

func appendBoolCompact(b []byte, v bool) ([]byte, error) {
	if v {
		return append(b, byte(ctBOOL_TRUE)), nil
	}
	return append(b, byte(ctBOOL_FALSE)), nil
}

func init() {
`)
	// Generate registration calls for all 12×12 combos
	allNames := make([]string, 0, 12)
	for _, s := range scalarTypes {
		allNames = append(allNames, s.name)
	}
	allNames = append(allNames, containerTypeNames...)

	for _, kn := range allNames {
		for _, vn := range allNames {
			fmt.Fprintf(w, "\tregisterMapAppendFuncCompact(t%s, t%s, appendMapCompact_%s_%s)\n",
				kn, vn, kn, vn)
		}
	}
	fmt.Fprintln(w, "}")

	// Generate functions for all 12×12 combos
	for _, kn := range allNames {
		for _, vn := range allNames {
			ks := isScalar(kn)
			vs := isScalar(vn)
			fname := fmt.Sprintf("appendMapCompact_%s_%s", kn, vn)

			if ks && vs {
				// Style A: fully specialized with range
				kt := scalarTypes[0]
				vt := scalarTypes[0]
				for _, s := range scalarTypes {
					if s.name == kn {
						kt = s
					}
					if s.name == vn {
						vt = s
					}
				}
				mapType := fmt.Sprintf("map[%s]%s", kt.goMapType, vt.goMapType)

				fmt.Fprintf(w, `
func %s(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	for k, v := range *(*%s)(p) {
		n--
		%s
		%s
	}
	return b, checkMapN(n)
}
`, fname, mapType, compactRangeKeyExpr(kt), compactRangeValExpr(vt))
			} else {
				// Style B: iterator-based with generic fallback
				var keyExpr, valExpr string
				if ks {
					kt := scalarTypes[0]
					for _, s := range scalarTypes {
						if s.name == kn {
							kt = s
						}
					}
					keyExpr = compactKeyExpr(kt)
				} else {
					keyExpr = `b, err = appendAnyCompact(t.K, b, kp); if err != nil { return b, err }`
				}
				if vs {
					vt := scalarTypes[0]
					for _, s := range scalarTypes {
						if s.name == vn {
							vt = s
						}
					}
					valExpr = compactValExpr(vt)
				} else {
					valExpr = `b, err = appendAnyCompact(t.V, b, vp); if err != nil { return b, err }`
				}

				fmt.Fprintf(w, `
func %s(t *tType, b []byte, p unsafe.Pointer) ([]byte, error) {
	b, n := appendCompactMapHeader(t, b, p)
	if n == 0 {
		return b, nil
	}
	var err error
	it := newMapIter(rvWithPtr(t.RV, p))
	for kp, vp := it.Next(); kp != nil; kp, vp = it.Next() {
		n--
		%s
		%s
	}
	return b, checkMapN(n)
}
`, fname, keyExpr, valExpr)
			}
		}
	}
}
