/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package reflect

import (
	"unsafe"

	"github.com/cloudwego/gopkg/protocol/thrift"
)

// This File is generated by xwrite_gen.sh. DO NOT EDIT.
// Template and code can be found in xwrite_list_gen_test.go.

func init() {
	registerXWriteListFunc(tBYTE, xwriteList_I08)
	registerXWriteListFunc(tI16, xwriteList_I16)
	registerXWriteListFunc(tI32, xwriteList_I32)
	registerXWriteListFunc(tI64, xwriteList_I64)
	registerXWriteListFunc(tDOUBLE, xwriteList_I64)
	registerXWriteListFunc(tENUM, xwriteList_ENUM)
	registerXWriteListFunc(tSTRING, xwriteList_STRING)
	registerXWriteListFunc(tSTRUCT, xwriteList_Other)
	registerXWriteListFunc(tMAP, xwriteList_Other)
	registerXWriteListFunc(tSET, xwriteList_Other)
	registerXWriteListFunc(tLIST, xwriteList_Other)
}

func xwriteList_I08(t *tType, b *thrift.XWriteBuffer, p unsafe.Pointer) error {
	t = t.V
	n, vp := xwriteListHeader(t, b, p)
	if n == 0 {
		return nil
	}
	for i := uint32(0); i < n; i++ {
		if i != 0 {
			vp = unsafe.Add(vp, t.Size)
		}
		thrift.XBuffer.WriteByte(b, *((*int8)(vp)))
	}
	return nil
}

func xwriteList_I16(t *tType, b *thrift.XWriteBuffer, p unsafe.Pointer) error {
	t = t.V
	n, vp := xwriteListHeader(t, b, p)
	if n == 0 {
		return nil
	}
	for i := uint32(0); i < n; i++ {
		if i != 0 {
			vp = unsafe.Add(vp, t.Size)
		}
		thrift.XBuffer.WriteI16(b, *((*int16)(vp)))
	}
	return nil
}

func xwriteList_I32(t *tType, b *thrift.XWriteBuffer, p unsafe.Pointer) error {
	t = t.V
	n, vp := xwriteListHeader(t, b, p)
	if n == 0 {
		return nil
	}
	for i := uint32(0); i < n; i++ {
		if i != 0 {
			vp = unsafe.Add(vp, t.Size)
		}
		thrift.XBuffer.WriteI32(b, *((*int32)(vp)))
	}
	return nil
}

func xwriteList_I64(t *tType, b *thrift.XWriteBuffer, p unsafe.Pointer) error {
	t = t.V
	n, vp := xwriteListHeader(t, b, p)
	if n == 0 {
		return nil
	}
	for i := uint32(0); i < n; i++ {
		if i != 0 {
			vp = unsafe.Add(vp, t.Size)
		}
		thrift.XBuffer.WriteI64(b, *((*int64)(vp)))
	}
	return nil
}

func xwriteList_ENUM(t *tType, b *thrift.XWriteBuffer, p unsafe.Pointer) error {
	t = t.V
	n, vp := xwriteListHeader(t, b, p)
	if n == 0 {
		return nil
	}
	for i := uint32(0); i < n; i++ {
		if i != 0 {
			vp = unsafe.Add(vp, t.Size)
		}
		thrift.XBuffer.WriteI32(b, int32(*((*int64)(vp))))
	}
	return nil
}

func xwriteList_STRING(t *tType, b *thrift.XWriteBuffer, p unsafe.Pointer) error {
	t = t.V
	n, vp := xwriteListHeader(t, b, p)
	if n == 0 {
		return nil
	}
	var s string
	for i := uint32(0); i < n; i++ {
		if i != 0 {
			vp = unsafe.Add(vp, t.Size)
		}
		s = *((*string)(vp))
		thrift.XBuffer.WriteString(b, s)
	}
	return nil
}

func xwriteList_Other(t *tType, b *thrift.XWriteBuffer, p unsafe.Pointer) error {
	t = t.V
	n, vp := xwriteListHeader(t, b, p)
	if n == 0 {
		return nil
	}
	var err error
	for i := uint32(0); i < n; i++ {
		if i != 0 {
			vp = unsafe.Add(vp, t.Size)
		}
		if t.IsPointer {
			err = t.XWriteFunc(t, b, *(*unsafe.Pointer)(vp))
		} else {
			err = t.XWriteFunc(t, b, vp)
		}
		if err != nil {
			return err
		}
	}
	return nil
}
