name: Tests

on: [ push, pull_request ]

jobs:
  unittest-amd64:
    strategy:
      matrix:
        go: [ "1.18", oldstable, stable ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test packages
        run: go test -race ./...
      - name: Test ./tests & Benchmark
        run: cd tests && go test -bench=. -benchmem -benchtime=100ms
