name: Tests

on: [ push, pull_request ]

jobs:
  unittest-amd64:
    strategy:
      matrix:
        go: [ "1.18", "1.19", "1.20", "1.21", "1.22", "1.23" ]
    runs-on: [ Linux, X64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # don't use cache for self-hosted runners
      - name: Test ./...
        run: go test -race ./...
      - name: Test ./tests
        run: cd tests && go test -race
      - name: Test Benchmark
        run: go test -bench=. -benchmem -run=none ./... -benchtime=100ms

  unittest-arm64:
    strategy:
      matrix:
        go: [ "1.18", "1.19", "1.20", "1.21", "1.22", "1.23" ]
    runs-on: [ ARM64 ] # It's OK under Linux or macOS
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # don't use cache for self-hosted runners
      - name: Test ./... # only tests reflect pkg, JIT pkgs is not supported
        run: go test -race ./internal/reflect
      - name: Test ./tests
        run: cd tests && go test -race
      - name: Test Benchmark
        run: go test -bench=. -benchmem -run=none ./internal/reflect -benchtime=100ms

  buildtag-amd64:
    strategy:
      matrix:
        go: [ "1.18", "1.23" ]
    runs-on: [ Linux, X64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # don't use cache for self-hosted runners
      - name: Build without frugal_jit
        run: go build -v ./...
      - name: Build with frugal_jit
        run: go build -v -tags=frugal_jit ./...
